name: raiwah
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/wasdee/raiwah

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  units_converter: ^3.0.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
