name: raiwah
description: A dart library measure area land in Thai unit.
version: 1.0.0
repository: https://github.com/wasdee/raiwah

environment:
  sdk: ^3.2.6

dependencies:
  units_converter: ^3.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
